In [1]:
import numpy as np
import pandas as pd

In [2]:
#1 Сгенерировать массив из положительных чисел произвольной длины. 
#Вывести элементы, которые больше среднего арифметического.
a = np.random.randint(1, 10000, np.random.randint(5, 55))
print(a[a > np.mean(a)])

[8774 7205 9429 8186 5676 5709 5687 5064 8530 8136 7532 9682 8216 6792
 6516 7084 6552 5941 7721 7648 5879 7175 9638 9932]


In [3]:
#2. Сгенерировать массив из 20 элементов, элементы которого лежат в интервале [0, 10].
# Определить количество элементов, отличающихся от минимального на 5.
# Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.
a = np.random.randint(0, 10, 20)
c = np.array([ ])
print(np.count_nonzero(a ==  min(a) + 5))
a = a[list(range(1, 20, 2))]
print(a[a % 2 == 0].mean())






1
6.5


In [4]:
#3. Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
# Возвести в квадрат максимальный элемент матрицы.
# Все четные числа заменить на 0.
a = np.random.randint(1, 10, (5, 5))
print(a.max() ** 2)
a[a % 2 == 0] = 0
print(a)



81
[[0 0 0 0 0]
 [7 9 0 9 0]
 [0 3 0 9 0]
 [0 5 9 0 0]
 [9 7 0 1 0]]


In [5]:
# 4.Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. 
# Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся
a = np.random.randint(-5, 5, (5, 5))
print(a)
for i in range(5):
    a[i][a[i] < 0] = len(a[i][a[i] < 0])
print(a)




[[ 1  3 -2 -2 -5]
 [ 2 -1 -3 -4 -5]
 [ 3  3  1 -3  2]
 [-1 -4 -1 -4 -2]
 [-2  4  4 -4 -2]]
[[1 3 3 3 3]
 [2 4 4 4 4]
 [3 3 1 1 2]
 [5 5 5 5 5]
 [3 4 4 3 3]]


In [6]:
df = pd.read_csv('titanic.csv')

In [7]:
# 1.Выведите распределение переменной __Pclass__ для мужчин и женщин.

#     Сколько мужчин было в первом классе?
#     Сколько женщин было в третьем классе?

print(pd.crosstab(df['Pclass'], df['Sex']))
((df['Pclass'] == 1) & (df['Sex'] == 'male')).sum(), ((df['Pclass'] == 3) & (df['Sex'] == 'female')).sum()



Sex     female  male
Pclass              
1           94   122
2           76   108
3          144   347


(122, 144)

In [8]:
# 2.Создайте новый признак __AgeGroup__, который равен:

#     1, если пассажир был моложе 30 лет;
#     2, если пассажиру было от 30 до 60 лет;
#     3, если пассажир был старше 60 лет.
df['Age'].fillna(df['Age'].median())
df['AgeGroup'] = df['Age'].apply(lambda x: 1 if x < 30 else (2 if x <= 60 else 3))
df.head()


Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  Sibsp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   AgeGroup  
0         1  
1         2  
2         1  
3         2  
4         2

In [9]:
#3. Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
df[(df['Embarked'] == 'C') & (df['Age'] > 50)]

Survived  Pclass                                              Name  \
54          0       1                    Ostby, Mr. Engelhart Cornelius   
96          0       1                         Goldschmidt, Mr. George B   
155         0       1                       Williams, Mr. Charles Duane   
174         0       1                           Smith, Mr. James Clinch   
195         1       1                              Lurette, Miss. Elise   
366         1       1  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)   
487         0       1                           Kent, Mr. Edward Austin   
493         0       1                           Artagaveytia, Mr. Ramon   
496         1       1                    Eustis, Miss. Elizabeth Mussey   
513         1       1    Rothschild, Mrs. Martin (Elizabeth L. Barrett)   
587         1       1                  Frolicher-Stehli, Mr. Maxmillian   
591         1       1   Stephenson, Mrs. Walter Bertram (Martha Eustis)   
647         1       1               Simonius-Blumer, Col. Oberst Alfons   
659         0       1                        Newell, Mr. Arthur Webster   
879         1       1     Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   

        Sex   Age  Sibsp  Parch    Ticket      Fare Cabin Embarked  AgeGroup  
54     male  65.0      0      1    113509   61.9792   B30        C         3  
96     male  71.0      0      0  PC 17754   34.6542    A5        C         3  
155    male  51.0      0      1  PC 17597   61.3792   NaN        C         2  
174    male  56.0      0      0     17764   30.6958    A7        C         2  
195  female  58.0      0      0  PC 17569  146.5208   B80        C         2  
366  female  60.0      1      0    110813   75.2500   D37        C         2  
487    male  58.0      0      0     11771   29.7000   B37        C         2  
493    male  71.0      0      0  PC 17609   49.5042   NaN        C         3  
496  female  54.0      1      0     36947   78.2667   D20        C         2  
513  female  54.0      1      0  PC 17603   59.4000   NaN        C         2  
587    male  60.0      1      1     13567   79.2000   B41        C         2  
591  female  52.0      1      0     36947   78.2667   D20        C         2  
647    male  56.0      0      0     13213   35.5000   A26        C         2  
659    male  58.0      0      2     35273  113.2750   D48        C         2  
879  female  56.0      0      1     11767   83.1583   C50        C         2

In [10]:
# 4.Выведите данные о всех женщинах младше 20 и старше 50 лет.
df[((df['Age'] < 20) | (df['Age'] > 50)) & (df['Sex'] == 'female')].head(10)

Survived  Pclass                                      Name     Sex   Age  \
9          1       2       Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
10         1       3           Sandstrom, Miss. Marguerite Rut  female   4.0   
11         1       1                  Bonnell, Miss. Elizabeth  female  58.0   
14         0       3      Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
15         1       2          Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
22         1       3               McGowan, Miss. Anna "Annie"  female  15.0   
24         0       3             Palsson, Miss. Torborg Danira  female   8.0   
38         0       3        Vander Planke, Miss. Augusta Maria  female  18.0   
39         1       3               Nicola-Yarred, Miss. Jamila  female  14.0   
43         1       2  Laroche, Miss. Simonne Marie Anne Andree  female   3.0   

    Sibsp  Parch         Ticket     Fare Cabin Embarked  AgeGroup  
9       1      0         237736  30.0708   NaN        C         1  
10      1      1        PP 9549  16.7000    G6        S         1  
11      0      0         113783  26.5500  C103        S         2  
14      0      0         350406   7.8542   NaN        S         1  
15      0      0         248706  16.0000   NaN        S         2  
22      0      0         330923   8.0292   NaN        Q         1  
24      3      1         349909  21.0750   NaN        S         1  
38      2      0         345764  18.0000   NaN        S         1  
39      1      0           2651  11.2417   NaN        C         1  
43      1      2  SC/Paris 2123  41.5792   NaN        C         1

In [11]:
# 5.Сколько пассажиров старше 70 лет было на борту?
(df['Age'] > 70).sum()

5

In [12]:
# 6.Посчитайте средний возраст среди мужчин и среди женщин.
df.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [13]:
# 7.Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
df.groupby('AgeGroup')['Survived'].mean()

AgeGroup
1    0.406250
2    0.418831
3    0.286432
Name: Survived, dtype: float64

In [14]:
# 8.Найдите максимальную стоимость билета в каждом из ценовых классов
df.groupby('Pclass')['Fare'].max()

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [15]:
# 9.Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.
df.pivot_table(['Age'], ['Sex'], aggfunc = 'mean')

Age
Sex              
female  27.915709
male    30.726645

In [16]:
pd.crosstab(df['Survived'], df['AgeGroup'],normalize = 1)

AgeGroup        1         2         3
Survived                             
0         0.59375  0.581169  0.713568
1         0.40625  0.418831  0.286432

In [17]:
df.pivot_table(['Fare'], ['Pclass'], aggfunc = 'max')

Fare
Pclass          
1       512.3292
2        73.5000
3        69.5500